import type { PageReport, Report, Severity } from "../types.js";

const ICON: Record<Severity, string> = { error: "🔴", warning: "🟡", info: "🔵", pass: "🟢" };

function bar(score: number): string {
  const filled = Math.round(score / 10);
  return "█".repeat(filled) + "░".repeat(10 - filled);
}

function pageSection(page: PageReport): string {
  const lines: string[] = [];
  lines.push(`## ${page.title ?? page.source}`);
  lines.push("");
  lines.push(`**Score: ${page.score}/100 (${page.grade})** \`${bar(page.score)}\` · \`${page.source}\``);
  lines.push("");

  lines.push("| Category | Score | ✓ | ⚠ | ✗ |");
  lines.push("| --- | --- | --- | --- | --- |");
  for (const c of page.categories) {
    lines.push(`| ${c.label} | ${c.score} | ${c.pass} | ${c.warning} | ${c.error} |`);
  }
  lines.push("");

  const issues = page.findings.filter((f) => f.severity === "error" || f.severity === "warning");
  if (issues.length) {
    lines.push("### Issues to fix");
    lines.push("");
    for (const f of issues) {
      lines.push(`- ${ICON[f.severity]} **${f.message}**${f.detail ? ` — _${f.detail}_` : ""}`);
      if (f.fix) lines.push(`  - 💡 ${f.fix}`);
    }
    lines.push("");
  }

  const tips = page.findings.filter((f) => f.severity === "info");
  if (tips.length) {
    lines.push("### Suggestions");
    lines.push("");
    for (const f of tips) lines.push(`- ${ICON.info} ${f.message}`);
    lines.push("");
  }

  return lines.join("\n");
}

/** Render a full report to Markdown. */
export function toMarkdown(report: Report): string {
  const lines: string[] = [];
  lines.push(`# aeolint report`);
  lines.push("");
  lines.push(
    `**Overall: ${report.summary.score}/100 (${report.summary.grade})** · ` +
      `${report.summary.pages} page(s) · ${report.summary.errors} error(s) · ${report.summary.warnings} warning(s)`,
  );
  lines.push("");
  lines.push(`> Generated by aeolint v${report.version} on ${report.generatedAt}`);
  lines.push("");
  for (const page of report.pages) lines.push(pageSection(page));
  return lines.join("\n").trimEnd() + "\n";
}
